version: '2'

services:
  nginx:
    build: ./nginx
    image: msiri/marcoucou-chat-ai:chat-nginx    
    ports:
        - 8080:80
    links:
        - back

  mongodb:
    build: ./data
    image: msiri/marcoucou-chat-ai:chat-mongodb
    ports:
        - 27017:27017    

  back:
    build: ./back
    image: msiri/marcoucou-chat-ai:chat-back    
    links:
        - mongodb
    depends_on: 
      - mongodb